[package]
name = "suricata-derive"
version = "7.0.0-beta1"
edition = "2018"

[lib]
proc-macro = true
path = "/home/drdave/s7-dv/rust/derive/src/lib.rs"

[dependencies]
proc-macro-crate = "= 1.1.0"
proc-macro2 = "1.0.36"
quote = "1.0"
syn = "1.0"
